--!strict
-- Designed for the CoS Rewrite. This script has been procedurally generated by C# code.
-- See https://github.com/EtiTheSpirit/CoSRewriteCreatureStruct for more information.

-- TARGET: ReplicatedStorage.CoreData.TypeDefinitions.IntrinsicCommon (ModuleScript)
-- PURPOSE: Provide a means of accessing intrinsic data of creatures. This is referenced by the runtime modules and must be secure.

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local EtiLibs = ReplicatedStorage.EtiLibs
local string = require(EtiLibs.Extension.String)
local math = require(EtiLibs.Extension.Math)
local table = require(EtiLibs.Extension.Table)

local IntrinsicHandlers = {
%%CS_INTRINSIC_BEHAVIORS%%
};

return table.freeze(IntrinsicHandlers)